# Players will have to wait this amount of seconds to send another report
report-cooldown: 20

# https://github.com/CortexPE/DiscordWebhookAPI virion is required to enable webhooks
enable-webhook: false
webhook-url: ""